draw_config:
  n_columns: 1
  separate_combo_diagrams: false
  combo_w: 26
  combo_h: 22
  key_w: 60
  key_h: 56
  split_gap: 30
  draw_key_sides: false
  svg_extra_style: |
    svg.keymap {
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
parse_config:
  zmk_additional_includes: ["behaviors.dtsi"]
  raw_binding_map:
    "&studio_unlock": "Studio\nUnlock"
    "&macro_ue": "ü"
    "&macro_ae": "ä"
    "&macro_oe": "ö"
    "&macro_gg": "gg"
    "&tmux_cmd N1": "Win 1"
    "&tmux_cmd N2": "Win 2"
    "&tmux_cmd N3": "Win 3"
    "&tmux_cmd N4": "Win 4"
    "&tmux_cmd N5": "Win 5"
    "&tmux_cmd N6": "Win 6"
    "&tmux_cmd N7": "Win 7"
    "&tmux_cmd N8": "Win 8"
    "&tmux_cmd N9": "Win 9"
    "&tmux_cmd N0": "Win 0"
    "&tmux_cmd D": "Detach"
    "&tmux_cmd V": "Split V"
    "&tmux_cmd H": "Split H"
    "&tmux_cmd C": "New Win"
    "&tmux_cmd W": "Tree"
    "&tmux_cmd O": "SessionX"
    "&tmux_cmd LS(H)": "Rsz ←"
    "&tmux_cmd LS(J)": "Rsz ↓"
    "&tmux_cmd LS(K)": "Rsz ↑"
    "&tmux_cmd LS(L)": "Rsz →"
    "&tmux_cmd COMMA": "Rename\nWin"
    "&tmux_cmd A": "Cheat\nSheet"
    "&tmux_cmd F": "Sessionzr"
    "&tmux_cmd LBKT": "Copy\nMode"
    "&tmux_cmd Z": "Zoom"
    "&tmux_cmd L": "Last\nWin"
    "&tmux_cmd LEFT": "Pane ←"
    "&tmux_cmd DOWN": "Pane ↓"
    "&tmux_cmd UP": "Pane ↑"
    "&tmux_cmd RIGHT": "Pane →"
    "&tmux_cmd SEMI": "Last\nPane"
    "&tmux_cmd R": "Reload"
    "&tmux_cmd P": "Floax"
    "&tmux_cmd LS(N)": "New\nSession"
    "&tmux_cmd RBKT": "Paste"
    "&tmux_cmd X": "Kill\nPane"
